# Generated by Django 5.1.2 on 2024-11-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True),
        ),
    ]
