# Generated by Django 5.1.2 on 2024-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slogan',
            field=models.CharField(default='Details in the Links', max_length=50),
        ),
    ]
